schema_version: 20180708
name: sendtobotfn
version: 0.0.38
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: sendtobotfn-trigger
  type: http
  source: /sendtobotfn-trigger
