schema_version: 20180708
name: receivefrombotfn
version: 0.0.21
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: receivefrombotfn-trigger
  type: http
  source: /receivefrombotfn-trigger
