schema_version: 20180708
name: createsnapshotfn
version: 0.0.9
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: createsnapshotfn-trigger
  type: http
  source: /createsnapshotfn-trigger
